[profile.default]
optimizer = true
optimizer_runs = 30_000
solc_version = '0.8.19'
src = 'contracts'
test = 'contracts/test'
out = 'artifacts'
cache_path  = 'cache'
libs = ['foundry-lib']
bytecode_hash = "none"
ffi = false

# default is zero, using a non-zero amount enables us to test e.g. billing based on gas prices.
gas_price = 1
block_timestamp = 1234567890
block_number = 12345

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

Test merge-request


Test merge. 



Test
